//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstApproach1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int SId { get; set; }
        public string Sname { get; set; }
        public int Fees { get; set; }
    }
}
