//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tble_Billing
    {
        public int Id { get; set; }
        public string BillId { get; set; }
        public string PatientName { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string Investigation { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Due { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Expense { get; set; }
        public Nullable<decimal> ReferalAmount { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
